name: cloth-comp
channels:
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=11.3
  - python=3.9
  - pytorch
  - torchvision
  - pip
  - pip:
    - pre-commit
    - ur_rtde
    - wandb
    - git+https://github.com/tlpss/camera-toolkit.git
    - git+https://github.com/airo-ugent/robotiq2F_tcp.git
    - git+https://github.com/tlpss/keypoint-detection.git
