name: cloth-comp
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - pre-commit
    - git+https://github.com/tlpss/camera-toolkit.git
    - -e git+https://github.com/airo-ugent/robotiq2F_tcp.git#egg=robotiq2F
    - ur_rtde
    - git+https://github.com/tlpss/keypoint-detection.git
